### ISSUE TITLE
I'm so confused by all the forks

### ISSUE THREAD

**Issue by nathany** [go-amz/amz#5]
I want to add CloudFront cache invalidation, but to where?

https://github.com/goamz/goamz already has some CloudFront stuff

https://github.com/mitchellh/goamz I've been using this fork up until now (due to #4).

also https://github.com/crowdmob/goamz

**Comment by nathany** [comment]
Thanks @dimitern.

It may be worth looking into https://www.clahub.com/ (disclaimer, I am also just a developer) or at least having a solid CONTRIBUTING.md file. Revel has a good example of [CONTRIBUTING](https://github.com/revel/revel/blob/master/CONTRIBUTING.md).

**Comment by niemeyer** [comment]
_> although I'm one of the maintainers of goamz the project is still lead by the original founder, Gustavo Niemeyer_

This is not accurate, as discussed before. Although I'm happy to try to help on this whenever feasible, the juju team at Canonical (that includes you, @dimitern :-) is the official maintainer of this package. That's where the package has been created, and where most of the recent changes originate and get reviewed and tested, so that team is in a much better position and have more resources to do a good job as the package maintainer than I am.

Also, please note that gopkg.in/amz.v1 is not yet another fork. This is the main repository that used to live in launchpad.net being moved over to GitHub, because @dimitern needs to land incompatible changes to bump the API revision up.
